apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmedapi
        image: user/vollmed:v2
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: dados
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /paciente
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
