name: Deploy_ecs

on:
  workflow_call:

jobs:

  ECS:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
  
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition tarefa_api-go --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: raphaelrlopes07/go_ci:${{ github.run_number }}
        environment-variables: |
            HOST=${{ secrets.DBHOST }}
            USER=${{ secrets.DBUSER }}
            PASSWORD=${{ secrets.DBPASSWORD }}
            DBNAME=${{ secrets.DBNAME }}
            DBPORT=${{ secrets.DBPORT }}
            PORT=8000

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
       task-definition: ${{ steps.task-def.outputs.task-definition }}
       service: go-service
       cluster: go-cluster
       wait-for-service-stability: true