machines = {
  "kali" => {"memory" => "2048", "cpu" => "1", "ip" => "20", "image" => "kalilinux/rolling"},
  "snort" => {"memory" => "2048", "cpu" => "1", "ip" => "21", "image" => "kalilinux/rolling"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: "MudeAquiParaosTresPrimeirosOctetos#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.gui = false
        
      end

      if "#{name}" == "snort"
        machine.vm.provision "shell", path: "script.sh"
      end

    end
  end
end