# Para estabelecer o CI/CD no gitlab, basta adicionar um ponto no início do nome do arquivo
stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t user/kubernetes-project:1.0 app/.
    - docker push user/kubernetes-project:1.0
  
deploy_gcp:

  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY

  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf /kubernetes-project && git clone repository && cd /kubernetes-project && ./script.sh"